apiVersion: v1
kind: Secret
metadata:
  name: queue-config
type: Opaque
data:
  URI: "MTI3LjAuMC4xOjExMzAwCg=="

---

apiVersion: oldmonk.evalsocket.in/v1
kind: QueueAutoScaler
metadata:
  name: lifecycle
spec:
  type : "BEANSTALKD"
  option :
    uri : '127.0.0.1:11300'
    tube: 'default'
    key : 'current-jobs-ready'
  secrets : queue-config
  maxPods : 6
  minPods : 1
  scaleDown :
    amount : 1
    threshold : 3
  scaleUp :
    amount : 1
    threshold : 4
  deployment : 'nginx-deployment'
  autopilot : true
  labels:
    env: dev
    app: nginx-deployment
    version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  appSpec: 
    - name: nginx
      image: nginx:1.15.4
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
          name: nginx-deployment
