apiVersion: oldmonk.evalsocket.in/v1
kind: QueueAutoScaler
metadata:
  name: sqsautoscalertest
spec:
  type : "SQS"
  option :
    uri : 'https://sqs.us-east-2.amazonaws.com/131220237071/tets'
    region : 'us-east-2'
  maxPods : 7
  minPods : 1
  scaleDown :
    amount : 4
    threshold : 8
  scaleUp :
    amount : 4
    threshold : 10
  deployment : 'demo-app2'
  autopilot : true
  secrets : 'demo'
  labels:
    chart: demo-app
    env: dev
    app: demo-app2
    version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  volume:
    - name: config-volume
      configMap:
        name: app-file-config
  appSpec :
    name : 'demo-app2'
    # readinessProbe:
    #   httpGet:
    #     path: /healthz
    #     port: 8080
    #   initialDelaySeconds: 3
    #   periodSeconds: 5
    # livenessProbe:
    #   httpGet:
    #     path: /healthz
    #     port: 8080
    #   initialDelaySeconds: 3
    #   periodSeconds: 5
    # revisionHistoryLimit: 4
    image: "nginx:latest"
    resources:
      requests:
        memory: 256Mi
        cpu: '0.5'
      limits:
        memory: 512Mi
        cpu: '1'
    # volumeMounts:
    #   - name: config-volume
    #     mountPath: /app/config.json
    # envFrom:
    #   - configMapRef:
    #     name: common-configmap
    #   - secretRef:
    #     name: app-config
    ports :
      - containerPort : 8080
