# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go fmt ./pkg/... ./cmd/... ./x/...
    - go mod tidy
    - go vet ./pkg/... ./cmd/... ./x/...
    - go generate ./pkg/... ./cmd/...
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/manager/main.go
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
    owner: evalsocket
    name: oldmonk
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- name: oldmonk
  github:
    owner: evalsocket
    name: homebrew-tap
  folder: Formula
  homepage: "https://github.com/evalsocket/oldmonk"
  description: "A QueueAutoScaler Operator for Kubernetes"
  install: bin.install "oldmonk"
