{{- if .Values.queues }}
{{- range $queue := .Values.queues }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "oldmonk.fullname" $ }}-queue-{{ $queue.name | replace "_" "-"}}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  URI: {{ $queue.uri | b64enc | quote }}
---
{{ end }}
{{ end }}