apiVersion: oldmonk.evalsocket.in/v1
kind: QueueAutoScaler
metadata:
  name: kafka
spec:
  type : "KAFKA"
  option :
    uri : '127.0.0.1:11300'
    group: 'default'
    topic : 'current-jobs-ready'
  maxPods : 6
  minPods : 1
  scaleDown :
    amount : 1
    threshold : 3
  scaleUp :
    amount : 1
    threshold : 4
  secrets : 'hhjvjh'
  deployment : 'demo-app2'
  labels:
    chart: demo-app
    env: dev
    app: demo-app2
    version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  volume:
    - name: config-volume
      configMap:
        name: app-file-config
  appSpec :
    name : 'demo-app2'
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 5
    revisionHistoryLimit: 4
    image: "nginx:latest"
    resources:
      requests:
        memory: 256Mi
        cpu: '0.5'
      limits:
        memory: 512Mi
        cpu: '1'
    volumeMounts:
      - name: config-volume
        mountPath: /app/config.json
    # envFrom:
    #   - configMapRef:
    #     name: common-configmap
    #   - secretRef:
    #     name: app-config
    ports :
      - containerPort : 8080
