apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: oldmonk
spec:
  version: "v0.0.1"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/evalsocket/oldmonk/releases/download/v0.0.1/oldmonk_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./oldmonk"
      to: "."
    bin: "oldmonk"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/evalsocket/oldmonk/releases/download/v0.0.1/oldmonk_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./oldmonk"
      to: "."
    bin: "oldmonk"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/evalsocket/oldmonk/releases/download/v0.0.1/oldmonk_windows_amd64.zip
    sha256: ""
    files:
    - from: "/oldmonk.exe"
      to: "."
    bin: "oldmonk.exe"
  shortDescription: A new plugin
  homepage: https://github.com/evalsocket/oldmonk
  caveats: |
    Usage:
      $ kubectl oldmonk
    For additional options:
      $ kubectl oldmonk --help
      or https://github.com/evalsocket/oldmonk/blob/v0.0.1/doc/USAGE.md
  description: |
    This is a new plugin
