name: unit-test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Go module cache
      id: go-mod-cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: go-mod-cache

    - name: Build
      run: go install -v ./...

    - name: Unit Test
      run: go test ./...
    
    - name: operator-sdk Docker build
      uses: xunholy/operator-sdk-action@master
      with:
          image: evalsocket/oldmonk
          tag: latest

    - uses: jerray/publish-docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: evalsocket/oldmonk
        tags: latest
